version: 2
updates:
  # Maintain dependencies for root pubspec
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
  # Maintain dependencies for just_ui_tokens package
  - package-ecosystem: "pub"
    directory: "/packages/tokens"
    schedule:
      interval: "weekly"
  # Maintain dependencies for just_ui_core package
  - package-ecosystem: "pub"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
  # Maintain dependencies for just_ui_cli package
  - package-ecosystem: "cargo"
    directory: "/packages/cli"
    schedule:
      interval: "weekly"
  # Maintain dependencies for docs apps
  - package-ecosystem: "npm"
    directory: "/apps/docs"
    schedule:
      interval: "weekly"
  # Maintain dependencies for showcase apps
  - package-ecosystem: "pub"
    directory: "/apps/showcase"
    schedule:
      interval: "weekly"
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
