import type { ThemeStudioState } from '@/lib/theme-studio-context';

/**
 * Converts a hex color string to 32-bit ARGB hex format used by Flutter Color.
 * E.g. '#a3e635' -> '0xFFA3E635'
 */
export function seedToArgbHex(hex: string): string {
  const clean = hex.replace(/^#/, '').toUpperCase();
  if (clean.length === 3) {
    const [r, g, b] = clean;
    return `0xFF${r}${r}${g}${g}${b}${b}`;
  }
  if (clean.length === 6) {
    return `0xFF${clean}`;
  }
  if (clean.length === 8) {
    return `0x${clean}`;
  }
  return '0xFFA3E635';
}

/**
 * Generates justui.config.yaml content reflecting the current studio state.
 */
export function generateYaml(
  state: Pick<ThemeStudioState, 'preset' | 'colorSpace'>,
  shareUrl?: string
): string {
  const urlComment = shareUrl
    ? `# ${shareUrl}`
    : '# https://justui.dev/en/studio';

  return `# justui.config.yaml
# Generated by JustUI Theme Studio
${urlComment}

components_dir: lib/widgets
tokens_dir: lib/tokens
shared_dir: lib/widgets/shared
registry_url: https://raw.githubusercontent.com/infinitedim/justui/main/registry
preset: ${state.preset}
color_space: ${state.colorSpace}
dart_target: standard
`;
}

export interface GenerateDartOptions {
  includeDefaults?: boolean;
}

/**
 * Generates Dart JustThemeData.fromSeed(...) configuration code.
 * Follows exact Dart signature from JustThemeData.fromSeed.
 */
export function generateDart(
  state: Pick<ThemeStudioState, 'seedColor' | 'isDark' | 'preset' | 'colorSpace'>,
  options?: GenerateDartOptions
): string {
  const argb = seedToArgbHex(state.seedColor);
  const includeDefaults = options?.includeDefaults ?? false;

  const params: string[] = [];

  const presetEnum =
    state.preset === 'default' ? '.default_' : `.${state.preset}`;

  if (includeDefaults) {
    params.push(`  isDark: ${state.isDark},`);
    params.push(`  preset: ${presetEnum},`);
    params.push(`  colorSpace: .${state.colorSpace},`);
  } else {
    if (state.isDark) {
      params.push('  isDark: true,');
    }
    if (state.preset !== 'default') {
      params.push(`  preset: ${presetEnum},`);
    }
    if (state.colorSpace !== 'hsl') {
      params.push(`  colorSpace: .${state.colorSpace},`);
    }
  }

  const paramsBlock = params.length > 0 ? `\n${params.join('\n')}\n` : '';

  return `import 'package:flutter/widgets.dart' show Color;
import 'package:just_ui_core/just_ui_core.dart';

final theme = JustThemeData.fromSeed(
  const Color(${argb}),${paramsBlock});
`;
}

/**
 * Generates justui CLI initialization command string.
 */
export function generateCli(
  state: Pick<ThemeStudioState, 'preset' | 'colorSpace'>
): string {
  return `justui init --preset ${state.preset} --color-space ${state.colorSpace}`;
}
