// justui-meta: registry=16147ecb289b201424e805f79fa0312c2302a55dfa4b3edd2b9589439b32cb9d local=de34c548ae0c508f454bbb894ea0e1b2a0be3ef2c0382a0303ab965458345e14
import 'package:flutter/material.dart' show ThemeMode;
import 'package:flutter/widgets.dart';
import '../../shared/just_tokens.dart';

// ============================================================
// JustUI Shared Theme Provider
// Auto-generated by JustUI CLI — do not edit manually.
// Lightweight copy of JustThemeProvider for copy-paste usage.
// ============================================================

// --- Motion Profile ---

class JustMotionProfile {
  final Duration instant;
  final Duration fast;
  final Duration normal;
  final Duration slow;
  final Duration slower;
  final Curve defaultCurve;
  final Curve enter;
  final Curve exit;
  final Curve spring;

  const JustMotionProfile({
    required this.instant,
    required this.fast,
    required this.normal,
    required this.slow,
    required this.slower,
    required this.defaultCurve,
    required this.enter,
    required this.exit,
    required this.spring,
  });

  JustMotionProfile resolve(BuildContext context) {
    if (MediaQuery.disableAnimationsOf(context)) return reduced;
    return this;
  }

  static const JustMotionProfile standard = JustMotionProfile(
    instant: JustDuration.instant,
    fast: JustDuration.fast,
    normal: JustDuration.normal,
    slow: JustDuration.slow,
    slower: JustDuration.slower,
    defaultCurve: JustCurves.default_,
    enter: JustCurves.enter,
    exit: JustCurves.exit,
    spring: JustCurves.spring,
  );

  static const JustMotionProfile reduced = JustMotionProfile(
    instant: Duration.zero,
    fast: Duration.zero,
    normal: Duration.zero,
    slow: Duration.zero,
    slower: Duration.zero,
    defaultCurve: Curves.linear,
    enter: Curves.linear,
    exit: Curves.linear,
    spring: Curves.linear,
  );

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JustMotionProfile &&
          instant == other.instant &&
          fast == other.fast &&
          normal == other.normal &&
          slow == other.slow &&
          slower == other.slower &&
          defaultCurve == other.defaultCurve &&
          enter == other.enter &&
          exit == other.exit &&
          spring == other.spring;

  @override
  int get hashCode => Object.hash(
    instant,
    fast,
    normal,
    slow,
    slower,
    defaultCurve,
    enter,
    exit,
    spring,
  );
}

// --- Radius Scheme ---

abstract class JustRadiusScheme {
  const JustRadiusScheme();
  Radius get none;
  Radius get xs;
  Radius get sm;
  Radius get md;
  Radius get lg;
  Radius get xl;
  Radius get xxl;
  Radius get full;
  JustRadiusScheme resolve(double width) => this;
}

class _DefaultRadiusScheme extends JustRadiusScheme {
  const _DefaultRadiusScheme();
  @override
  Radius get none => JustRadius.none;
  @override
  Radius get xs => JustRadius.xs;
  @override
  Radius get sm => JustRadius.sm;
  @override
  Radius get md => JustRadius.md;
  @override
  Radius get lg => JustRadius.lg;
  @override
  Radius get xl => JustRadius.xl;
  @override
  Radius get xxl => JustRadius.xxl;
  @override
  Radius get full => JustRadius.full;
}

// --- Spacing Scheme ---

abstract class JustSpacingScheme {
  const JustSpacingScheme();
  double get xxs;
  double get xs;
  double get sm;
  double get md;
  double get lg;
  double get xl;
  double get xxl;
  double get xxxl;
  double get huge;
  JustSpacingScheme resolve(double width) => this;
}

class _DefaultSpacingScheme extends JustSpacingScheme {
  const _DefaultSpacingScheme();
  @override
  double get xxs => JustSpacing.xxs;
  @override
  double get xs => JustSpacing.xs;
  @override
  double get sm => JustSpacing.sm;
  @override
  double get md => JustSpacing.md;
  @override
  double get lg => JustSpacing.lg;
  @override
  double get xl => JustSpacing.xl;
  @override
  double get xxl => JustSpacing.xxl;
  @override
  double get xxxl => JustSpacing.xxxl;
  @override
  double get huge => JustSpacing.huge;
}

// --- Shadow Scheme ---

abstract class JustShadowScheme {
  const JustShadowScheme();
  List<BoxShadow> get xs;
  List<BoxShadow> get sm;
  List<BoxShadow> get md;
  List<BoxShadow> get lg;
  List<BoxShadow> get xl;
  List<BoxShadow> get xxl;
}

class _DefaultShadowScheme extends JustShadowScheme {
  const _DefaultShadowScheme();
  @override
  List<BoxShadow> get xs => JustShadows.xs;
  @override
  List<BoxShadow> get sm => JustShadows.sm;
  @override
  List<BoxShadow> get md => JustShadows.md;
  @override
  List<BoxShadow> get lg => JustShadows.lg;
  @override
  List<BoxShadow> get xl => JustShadows.xl;
  @override
  List<BoxShadow> get xxl => JustShadows.xxl;
}

class NeobrutalismShadowScheme extends JustShadowScheme {
  final Color shadowColor;
  const NeobrutalismShadowScheme({this.shadowColor = const Color(0xFF000000)});
  @override
  List<BoxShadow> get xs => [
    BoxShadow(offset: const Offset(2, 2), color: shadowColor),
  ];
  @override
  List<BoxShadow> get sm => [
    BoxShadow(offset: const Offset(2, 2), color: shadowColor),
  ];
  @override
  List<BoxShadow> get md => [
    BoxShadow(offset: const Offset(4, 4), color: shadowColor),
  ];
  @override
  List<BoxShadow> get lg => [
    BoxShadow(offset: const Offset(6, 6), color: shadowColor),
  ];
  @override
  List<BoxShadow> get xl => [
    BoxShadow(offset: const Offset(6, 6), color: shadowColor),
  ];
  @override
  List<BoxShadow> get xxl => [
    BoxShadow(offset: const Offset(8, 8), color: shadowColor),
  ];
}

// --- Theme Data ---

class JustThemeData {
  final JustColorScheme colors;
  final JustSpacingScheme spacing;
  final JustRadiusScheme radius;
  final JustShadowScheme shadows;
  final JustMotionProfile animations;
  final JustThemePreset preset;

  const JustThemeData({
    required this.colors,
    this.spacing = const _DefaultSpacingScheme(),
    this.radius = const _DefaultRadiusScheme(),
    this.shadows = const _DefaultShadowScheme(),
    this.animations = JustMotionProfile.standard,
    this.preset = JustThemePreset.default_,
  });

  static final JustThemeData light = JustThemeData(
    colors: JustColors.lightScheme,
    preset: JustThemePreset.default_,
  );

  static final JustThemeData dark = JustThemeData(
    colors: JustColors.darkScheme,
    preset: JustThemePreset.default_,
  );

  static final JustThemeData neobrutalismLight = JustThemeData(
    colors: JustColors.neobrutalismLightScheme,
    shadows: const NeobrutalismShadowScheme(),
    preset: JustThemePreset.neobrutalism,
  );

  static final JustThemeData neobrutalismDark = JustThemeData(
    colors: JustColors.neobrutalismDarkScheme,
    shadows: const NeobrutalismShadowScheme(shadowColor: Color(0xFFFFFFFF)),
    preset: JustThemePreset.neobrutalism,
  );

  Offset get shadowOffset =>
      preset == JustThemePreset.neobrutalism ? const Offset(3.0, 3.0) : .zero;

  List<BoxShadow> resolveShadows(
    List<BoxShadow> baseShadows, {
    required bool isPressed,
  }) {
    if (preset == JustThemePreset.neobrutalism && isPressed) {
      return baseShadows.map((s) => s.copyWith(offset: .zero)).toList();
    }
    return baseShadows;
  }

  Widget buildPressEffect({
    required Widget child,
    required bool isPressed,
    double scaleFactor = 0.97,
    Offset? translationOffset,
  }) {
    if (preset == JustThemePreset.neobrutalism) {
      final offset = translationOffset ?? shadowOffset;
      return AnimatedContainer(
        duration: animations.instant,
        curve: animations.defaultCurve,
        transform: Matrix4.translationValues(
          isPressed ? offset.dx : 0.0,
          isPressed ? offset.dy : 0.0,
          0.0,
        ),
        child: child,
      );
    }
    return AnimatedScale(
      scale: isPressed ? scaleFactor : 1.0,
      duration: animations.instant,
      curve: animations.defaultCurve,
      child: child,
    );
  }

  JustThemeData copyWith({
    JustColorScheme? colors,
    JustSpacingScheme? spacing,
    JustRadiusScheme? radius,
    JustShadowScheme? shadows,
    JustMotionProfile? animations,
    JustThemePreset? preset,
  }) {
    return JustThemeData(
      colors: colors ?? this.colors,
      spacing: spacing ?? this.spacing,
      radius: radius ?? this.radius,
      shadows: shadows ?? this.shadows,
      animations: animations ?? this.animations,
      preset: preset ?? this.preset,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is JustThemeData &&
          colors == other.colors &&
          spacing == other.spacing &&
          radius == other.radius &&
          shadows == other.shadows &&
          animations == other.animations &&
          preset == other.preset;

  @override
  int get hashCode =>
      Object.hash(colors, spacing, radius, shadows, animations, preset);
}

// --- Aspect Enum ---

enum JustThemeAspect {
  colors,
  typography,
  spacing,
  radius,
  shadows,
  animations,
  preset,
}

// --- Theme Provider ---

class JustThemeProvider extends StatefulWidget {
  const JustThemeProvider({
    super.key,
    required this.child,
    this.onThemeChanged,
    this.initialThemeMode,
    this.lightTheme,
    this.darkTheme,
    this.transitionDuration = JustDuration.normal,
    this.transitionCurve = JustCurves.default_,
  });

  final Widget child;
  final void Function(ThemeMode)? onThemeChanged;
  final ThemeMode? initialThemeMode;
  final JustThemeData? lightTheme;
  final JustThemeData? darkTheme;
  final Duration transitionDuration;
  final Curve transitionCurve;

  @override
  State<JustThemeProvider> createState() => JustThemeProviderState();

  static JustThemeProviderState of(
    BuildContext context, {
    JustThemeAspect? aspect,
  }) {
    final model = InheritedModel.inheritFrom<_JustThemeModel>(
      context,
      aspect: aspect,
    );
    if (model == null) {
      throw FlutterError('JustThemeProvider was not found in the widget tree.');
    }
    return model.state;
  }

  static JustThemeProviderState read(BuildContext context) {
    final element = context
        .getElementForInheritedWidgetOfExactType<_JustThemeModel>();
    if (element == null) {
      throw FlutterError('JustThemeProvider was not found in the widget tree.');
    }
    return (element.widget as _JustThemeModel).state;
  }
}

class JustThemeProviderState extends State<JustThemeProvider>
    with WidgetsBindingObserver {
  late ThemeMode _themeMode;
  late JustThemeData _lightTheme;
  late JustThemeData _darkTheme;

  ThemeMode get themeMode => _themeMode;
  Duration get transitionDuration => widget.transitionDuration;
  Curve get transitionCurve => widget.transitionCurve;

  JustThemeData get theme {
    final JustThemeData baseTheme;
    switch (_themeMode) {
      case .light:
        baseTheme = _lightTheme;
        break;
      case .dark:
        baseTheme = _darkTheme;
        break;
      case .system:
        final brightness =
            WidgetsBinding.instance.platformDispatcher.platformBrightness;
        baseTheme = brightness == .dark ? _darkTheme : _lightTheme;
        break;
    }

    final double width = MediaQuery.maybeSizeOf(context)?.width ?? 1024.0;
    final resolvedAnimations = baseTheme.animations.resolve(context);

    return baseTheme.copyWith(
      spacing: baseTheme.spacing.resolve(width),
      radius: baseTheme.radius.resolve(width),
      animations: resolvedAnimations,
    );
  }

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    _themeMode = widget.initialThemeMode ?? .system;
    _lightTheme = widget.lightTheme ?? .light;
    _darkTheme = widget.darkTheme ?? .dark;
  }

  @override
  void dispose() {
    WidgetsBinding.instance.removeObserver(this);
    super.dispose();
  }

  @override
  void didUpdateWidget(covariant JustThemeProvider oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (widget.lightTheme != oldWidget.lightTheme) {
      _lightTheme = widget.lightTheme ?? .light;
    }
    if (widget.darkTheme != oldWidget.darkTheme) {
      _darkTheme = widget.darkTheme ?? .dark;
    }
  }

  @override
  void didChangePlatformBrightness() {
    if (_themeMode == .system) setState(() {});
  }

  void setThemeMode(ThemeMode mode) {
    if (_themeMode == mode) return;
    setState(() => _themeMode = mode);
    widget.onThemeChanged?.call(mode);
  }

  void toggleTheme() {
    setThemeMode(_themeMode == .light ? .dark : .light);
  }

  void applyTheme({JustThemeData? light, JustThemeData? dark}) {
    setState(() {
      if (light != null) _lightTheme = light;
      if (dark != null) _darkTheme = dark;
    });
  }

  @override
  Widget build(BuildContext context) {
    return _JustThemeModel(
      state: this,
      themeMode: _themeMode,
      themeData: theme,
      child: widget.child,
    );
  }
}

class _JustThemeModel extends InheritedModel<JustThemeAspect> {
  const _JustThemeModel({
    required this.state,
    required this.themeMode,
    required this.themeData,
    required super.child,
  });

  final JustThemeProviderState state;
  final ThemeMode themeMode;
  final JustThemeData themeData;

  @override
  bool updateShouldNotify(_JustThemeModel oldWidget) =>
      themeMode != oldWidget.themeMode || themeData != oldWidget.themeData;

  @override
  bool updateShouldNotifyDependent(
    _JustThemeModel oldWidget,
    Set<JustThemeAspect> dependencies,
  ) {
    if (dependencies.contains(JustThemeAspect.colors) &&
        themeData.colors != oldWidget.themeData.colors) {
      return true;
    }
    if (dependencies.contains(JustThemeAspect.spacing) &&
        themeData.spacing != oldWidget.themeData.spacing) {
      return true;
    }
    if (dependencies.contains(JustThemeAspect.radius) &&
        themeData.radius != oldWidget.themeData.radius) {
      return true;
    }
    if (dependencies.contains(JustThemeAspect.shadows) &&
        themeData.shadows != oldWidget.themeData.shadows) {
      return true;
    }
    if (dependencies.contains(JustThemeAspect.animations) &&
        themeData.animations != oldWidget.themeData.animations) {
      return true;
    }
    if (dependencies.contains(JustThemeAspect.preset) &&
        themeData.preset != oldWidget.themeData.preset) {
      return true;
    }
    return false;
  }
}
