/**
 * Generates `src/lib/components.generated.ts` from `registry/index.json`
 * (which components exist, their slug, category, files and dependencies)
 * and from the Rust CLI sources (its version and default paths/URL), so the
 * site never hand-types a fact the registry or CLI already owns. Run after
 * any registry or CLI release change:
 *
 *   bun run generate:components
 *
 * Or check for drift without writing (used in CI):
 *
 *   bun run generate:components -- --check
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
// prettier's CJS export shape confuses the import resolver's default-export
// check; the named exports used below exist at runtime.
// eslint-disable-next-line import/default
import prettier from 'prettier';

// The registry has historically had a `forms` (plural) typo for `slider`;
// normalize known aliases here rather than trusting the raw value blindly.
const CATEGORY_ALIASES: Record<string, string> = { forms: 'form' };

interface RegistryFile {
  name: string;
  path: string;
}

interface RegistryComponent {
  name: string;
  category?: string;
  internal?: boolean;
  description?: string;
  registryDependencies?: string[];
  supportedPresets?: string[];
  files?: Record<string, RegistryFile[]>;
}

interface RegistryIndex {
  version: string;
  presets?: string[];
  components: RegistryComponent[];
}

interface CliFacts {
  version: string;
  registryUrl: string;
  componentsDir: string;
  sharedDir: string;
  tokensDir: string;
}

function matchOrThrow(source: string, pattern: RegExp, what: string): string {
  const match = pattern.exec(source);
  if (!match?.[1]) {
    throw new Error(`Could not find ${what} in the CLI sources.`);
  }
  return match[1];
}

function readCliFacts(cliRoot: string): CliFacts {
  const cargo = readFileSync(path.join(cliRoot, 'Cargo.toml'), 'utf-8');
  const config = readFileSync(path.join(cliRoot, 'src/config.rs'), 'utf-8');
  return {
    version: matchOrThrow(cargo, /^version\s*=\s*"([^"]+)"/m, 'version'),
    registryUrl: matchOrThrow(
      config,
      /DEFAULT_REGISTRY_URL:[^=]*=\s*"([^"]+)"/,
      'DEFAULT_REGISTRY_URL'
    ),
    componentsDir: matchOrThrow(
      config,
      /components_dir:\s*"([^"]+)"\.to_string\(\)/,
      'default components_dir'
    ),
    sharedDir: matchOrThrow(
      config,
      /shared_dir:\s*"([^"]+)"\.to_string\(\)/,
      'default shared_dir'
    ),
    tokensDir: matchOrThrow(
      config,
      /tokens_dir:\s*"([^"]+)"\.to_string\(\)/,
      'default tokens_dir'
    ),
  };
}

// Prettier (singleQuote) normalizes the quote style afterwards; JSON
// escaping keeps apostrophes and non-ASCII characters in descriptions safe.
function quote(value: string): string {
  return JSON.stringify(value).replace(
    /[\u0080-\uffff]/g,
    (ch) => `\\u${ch.charCodeAt(0).toString(16).padStart(4, '0')}`
  );
}

function quoteList(values: readonly string[]): string {
  return `[${values.map(quote).join(', ')}]`;
}

function toPascalCase(slug: string): string {
  return slug
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/**
 * The CLI registers a component's ThemeExtension after copying it, reading
 * the class name from the theme file itself; do the same here.
 */
function readThemeClass(
  registryRoot: string,
  files: readonly RegistryFile[]
): string | null {
  for (const file of files) {
    if (!file.name.endsWith('_theme.dart')) continue;
    const source = readFileSync(path.join(registryRoot, file.path), 'utf-8');
    // Same rule as extract_theme_class_name() in packages/cli/src/commands/add.rs.
    if (!source.includes('extends ThemeExtension')) continue;
    const match = /class\s+(?:const\s+)?([A-Za-z0-9_]+Theme(?:Data)?)/.exec(
      source
    );
    if (match?.[1]) return match[1];
  }
  return null;
}

function generateContent(
  registry: RegistryIndex,
  cli: CliFacts,
  registryRoot: string
): {
  content: string;
  count: number;
} {
  const publicComponents = registry.components
    .filter(
      (c) => !c.internal && c.category !== 'tokens' && c.category !== 'core'
    )
    .map((c) => ({
      name: `Just${toPascalCase(c.name)}`,
      slug: c.name,
      category: CATEGORY_ALIASES[c.category ?? ''] ?? c.category ?? 'primitive',
    }))
    .sort((a, b) => a.slug.localeCompare(b.slug));

  const lines = [
    '// AUTO-GENERATED by scripts/generate-components-data.ts - do not edit by hand.',
    '// Sources: registry/index.json and packages/cli. Regenerate with `bun run generate:components`.',
    '',
    'export type GeneratedComponentCategory =',
    "  | 'primitive'",
    "  | 'selection'",
    "  | 'layout'",
    "  | 'form'",
    "  | 'navigation'",
    "  | 'overlay'",
    "  | 'composite';",
    '',
    'export interface GeneratedComponentMeta {',
    '  readonly name: string;',
    '  readonly slug: string;',
    '  readonly category: GeneratedComponentCategory;',
    '}',
    '',
    'export const GENERATED_COMPONENTS: readonly GeneratedComponentMeta[] = [',
    ...publicComponents.map(
      (c) =>
        `  { name: '${c.name}', slug: '${c.slug}', category: '${c.category}' },`
    ),
    '] as const;',
    '',
    '/** `version` in packages/cli/Cargo.toml. */',
    `export const CLI_VERSION = ${quote(cli.version)};`,
    '/** `version` in registry/index.json. */',
    `export const REGISTRY_VERSION = ${quote(registry.version)};`,
    `export const REGISTRY_PRESETS: readonly string[] = ${quoteList(registry.presets ?? [])};`,
    '',
    '/** Defaults from packages/cli/src/config.rs (`justui init -y`). */',
    'export const CLI_DEFAULTS = {',
    `  registryUrl: ${quote(cli.registryUrl)},`,
    `  componentsDir: ${quote(cli.componentsDir)},`,
    `  sharedDir: ${quote(cli.sharedDir)},`,
    `  tokensDir: ${quote(cli.tokensDir)},`,
    '} as const;',
    '',
    'export interface GeneratedRegistryEntry {',
    '  readonly name: string;',
    '  readonly category: string;',
    '  readonly internal: boolean;',
    '  readonly description: string;',
    '  /** File names in the order the CLI copies them (common, then default). */',
    '  readonly files: readonly string[];',
    '  readonly registryDependencies: readonly string[];',
    '  readonly supportedPresets: readonly string[];',
    '  /** ThemeExtension the CLI registers in theme_data_material.dart. */',
    '  readonly themeClass: string | null;',
    '}',
    '',
    '/** Every registry entry, internal ones included, in registry order. */',
    'export const GENERATED_REGISTRY: readonly GeneratedRegistryEntry[] = [',
    ...registry.components.map((c) => {
      const registryFiles = [
        ...(c.files?.common ?? []),
        ...(c.files?.default ?? []),
      ];
      const files = registryFiles.map((f) => f.name);
      const themeClass = readThemeClass(registryRoot, registryFiles);
      return [
        '  {',
        `    name: ${quote(c.name)},`,
        `    category: ${quote(CATEGORY_ALIASES[c.category ?? ''] ?? c.category ?? 'primitive')},`,
        `    internal: ${c.internal === true},`,
        `    description: ${quote(c.description ?? '')},`,
        `    files: ${quoteList(files)},`,
        `    registryDependencies: ${quoteList(c.registryDependencies ?? [])},`,
        `    supportedPresets: ${quoteList(c.supportedPresets ?? [])},`,
        `    themeClass: ${themeClass ? quote(themeClass) : 'null'},`,
        '  },',
      ].join('\n');
    }),
    '] as const;',
    '',
  ];

  return { content: lines.join('\n'), count: publicComponents.length };
}

async function main() {
  const checkOnly = process.argv.includes('--check');
  const registryPath = path.resolve(__dirname, '../../../registry/index.json');
  const cliRoot = path.resolve(__dirname, '../../../packages/cli');
  const outPath = path.resolve(__dirname, '../src/lib/components.generated.ts');

  const registry = JSON.parse(
    readFileSync(registryPath, 'utf-8')
  ) as RegistryIndex;
  const { content: rawContent, count } = generateContent(
    registry,
    readCliFacts(cliRoot),
    path.dirname(registryPath)
  );
  // Format through the project's own Prettier config so the checked-in
  // output is byte-stable and `--check` doesn't flag cosmetic drift.
  const prettierConfig = (await prettier.resolveConfig(outPath)) ?? {};
  const content = await prettier.format(rawContent, {
    ...prettierConfig,
    filepath: outPath,
  });

  if (checkOnly) {
    let existing = '';
    try {
      existing = readFileSync(outPath, 'utf-8');
    } catch {
      // File doesn't exist yet - treated as drifted below.
    }
    if (existing !== content) {
      console.error(
        `${path.relative(process.cwd(), outPath)} is out of date with registry/index.json.\n` +
          'Run `bun run generate:components` and commit the result.'
      );
      process.exit(1);
    }
    console.log(`${path.relative(process.cwd(), outPath)} is up to date.`);
    return;
  }

  writeFileSync(outPath, content);
  console.log(
    `Wrote ${count} components to ${path.relative(process.cwd(), outPath)}`
  );
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
