/**
 * Generates `src/lib/components.generated.ts` from `registry/index.json`,
 * the canonical source of truth for which components exist, their slug,
 * and their category. Run after any registry change:
 *
 *   bun run generate:components
 *
 * Or check for drift without writing (used in CI):
 *
 *   bun run generate:components -- --check
 */
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
// prettier's CJS export shape confuses the import resolver's default-export
// check; the named exports used below exist at runtime.
// eslint-disable-next-line import/default
import prettier from 'prettier';

// The registry has historically had a `forms` (plural) typo for `slider`;
// normalize known aliases here rather than trusting the raw value blindly.
const CATEGORY_ALIASES: Record<string, string> = { forms: 'form' };

interface RegistryComponent {
  name: string;
  category?: string;
  internal?: boolean;
}

interface RegistryIndex {
  components: RegistryComponent[];
}

function toPascalCase(slug: string): string {
  return slug
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

function generateContent(registry: RegistryIndex): {
  content: string;
  count: number;
} {
  const publicComponents = registry.components
    .filter(
      (c) => !c.internal && c.category !== 'tokens' && c.category !== 'core'
    )
    .map((c) => ({
      name: `Just${toPascalCase(c.name)}`,
      slug: c.name,
      category: CATEGORY_ALIASES[c.category ?? ''] ?? c.category ?? 'primitive',
    }))
    .sort((a, b) => a.slug.localeCompare(b.slug));

  const lines = [
    '// AUTO-GENERATED by scripts/generate-components-data.ts - do not edit by hand.',
    '// Source of truth: registry/index.json. Regenerate with `bun run generate:components`.',
    '',
    'export type GeneratedComponentCategory =',
    "  | 'primitive'",
    "  | 'selection'",
    "  | 'layout'",
    "  | 'form'",
    "  | 'navigation'",
    "  | 'overlay'",
    "  | 'composite';",
    '',
    'export interface GeneratedComponentMeta {',
    '  readonly name: string;',
    '  readonly slug: string;',
    '  readonly category: GeneratedComponentCategory;',
    '}',
    '',
    'export const GENERATED_COMPONENTS: readonly GeneratedComponentMeta[] = [',
    ...publicComponents.map(
      (c) =>
        `  { name: '${c.name}', slug: '${c.slug}', category: '${c.category}' },`
    ),
    '] as const;',
    '',
  ];

  return { content: lines.join('\n'), count: publicComponents.length };
}

async function main() {
  const checkOnly = process.argv.includes('--check');
  const registryPath = path.resolve(__dirname, '../../../registry/index.json');
  const outPath = path.resolve(__dirname, '../src/lib/components.generated.ts');

  const registry = JSON.parse(
    readFileSync(registryPath, 'utf-8')
  ) as RegistryIndex;
  const { content: rawContent, count } = generateContent(registry);
  // Format through the project's own Prettier config so the checked-in
  // output is byte-stable and `--check` doesn't flag cosmetic drift.
  const prettierConfig = (await prettier.resolveConfig(outPath)) ?? {};
  const content = await prettier.format(rawContent, {
    ...prettierConfig,
    filepath: outPath,
  });

  if (checkOnly) {
    let existing = '';
    try {
      existing = readFileSync(outPath, 'utf-8');
    } catch {
      // File doesn't exist yet - treated as drifted below.
    }
    if (existing !== content) {
      console.error(
        `${path.relative(process.cwd(), outPath)} is out of date with registry/index.json.\n` +
          'Run `bun run generate:components` and commit the result.'
      );
      process.exit(1);
    }
    console.log(`${path.relative(process.cwd(), outPath)} is up to date.`);
    return;
  }

  writeFileSync(outPath, content);
  console.log(
    `Wrote ${count} components to ${path.relative(process.cwd(), outPath)}`
  );
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
