name: just_ui_core
description: Core UI library for JustUI including the high-performance theming engine and responsive utilities.
version: 0.10.0
publish_to: none

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.41.0"

dependencies:
  flutter:
    sdk: flutter
  just_ui_tokens:
    path: ../tokens

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
