// AUTO-GENERATED by scripts/generate-components-data.ts - do not edit by hand.
// Source of truth: registry/index.json. Regenerate with `bun run generate:components`.

export type GeneratedComponentCategory =
  | 'primitive'
  | 'selection'
  | 'layout'
  | 'form'
  | 'navigation'
  | 'overlay'
  | 'composite';

export interface GeneratedComponentMeta {
  readonly name: string;
  readonly slug: string;
  readonly category: GeneratedComponentCategory;
}

export const GENERATED_COMPONENTS: readonly GeneratedComponentMeta[] = [
  { name: 'JustAccordion', slug: 'accordion', category: 'primitive' },
  { name: 'JustAvatar', slug: 'avatar', category: 'primitive' },
  { name: 'JustAvatarGroup', slug: 'avatar-group', category: 'composite' },
  { name: 'JustBadge', slug: 'badge', category: 'primitive' },
  { name: 'JustBottomNav', slug: 'bottom-nav', category: 'navigation' },
  { name: 'JustBreadcrumb', slug: 'breadcrumb', category: 'navigation' },
  { name: 'JustButton', slug: 'button', category: 'primitive' },
  { name: 'JustCard', slug: 'card', category: 'layout' },
  { name: 'JustCarousel', slug: 'carousel', category: 'layout' },
  { name: 'JustCheckbox', slug: 'checkbox', category: 'selection' },
  { name: 'JustDatePicker', slug: 'date-picker', category: 'composite' },
  {
    name: 'JustDateRangePicker',
    slug: 'date-range-picker',
    category: 'composite',
  },
  { name: 'JustDialog', slug: 'dialog', category: 'overlay' },
  { name: 'JustIconButton', slug: 'icon-button', category: 'composite' },
  { name: 'JustInput', slug: 'input', category: 'primitive' },
  { name: 'JustProgress', slug: 'progress', category: 'primitive' },
  { name: 'JustRadio', slug: 'radio', category: 'selection' },
  { name: 'JustRadioGroup', slug: 'radio-group', category: 'composite' },
  { name: 'JustResizable', slug: 'resizable', category: 'layout' },
  { name: 'JustScrollArea', slug: 'scroll-area', category: 'layout' },
  { name: 'JustSelect', slug: 'select', category: 'primitive' },
  { name: 'JustSeparator', slug: 'separator', category: 'layout' },
  { name: 'JustSheet', slug: 'sheet', category: 'overlay' },
  { name: 'JustSidebar', slug: 'sidebar', category: 'navigation' },
  { name: 'JustSkeleton', slug: 'skeleton', category: 'layout' },
  { name: 'JustSlider', slug: 'slider', category: 'form' },
  { name: 'JustSwitch', slug: 'switch', category: 'selection' },
  { name: 'JustTable', slug: 'table', category: 'primitive' },
  { name: 'JustTabs', slug: 'tabs', category: 'navigation' },
  { name: 'JustTimePicker', slug: 'time-picker', category: 'composite' },
  { name: 'JustToast', slug: 'toast', category: 'overlay' },
  { name: 'JustToggle', slug: 'toggle', category: 'primitive' },
  { name: 'JustTooltip', slug: 'tooltip', category: 'overlay' },
] as const;
