// AUTO-GENERATED by scripts/generate-components-data.ts - do not edit by hand.
// Sources: registry/index.json and packages/cli. Regenerate with `bun run generate:components`.

export type GeneratedComponentCategory =
  | 'primitive'
  | 'selection'
  | 'layout'
  | 'form'
  | 'navigation'
  | 'overlay'
  | 'composite';

export interface GeneratedComponentMeta {
  readonly name: string;
  readonly slug: string;
  readonly category: GeneratedComponentCategory;
}

export const GENERATED_COMPONENTS: readonly GeneratedComponentMeta[] = [
  { name: 'JustAccordion', slug: 'accordion', category: 'primitive' },
  { name: 'JustAvatar', slug: 'avatar', category: 'primitive' },
  { name: 'JustAvatarGroup', slug: 'avatar-group', category: 'composite' },
  { name: 'JustBadge', slug: 'badge', category: 'primitive' },
  { name: 'JustBottomNav', slug: 'bottom-nav', category: 'navigation' },
  { name: 'JustBreadcrumb', slug: 'breadcrumb', category: 'navigation' },
  { name: 'JustButton', slug: 'button', category: 'primitive' },
  { name: 'JustCard', slug: 'card', category: 'layout' },
  { name: 'JustCarousel', slug: 'carousel', category: 'layout' },
  { name: 'JustCheckbox', slug: 'checkbox', category: 'selection' },
  { name: 'JustDatePicker', slug: 'date-picker', category: 'composite' },
  {
    name: 'JustDateRangePicker',
    slug: 'date-range-picker',
    category: 'composite',
  },
  { name: 'JustDialog', slug: 'dialog', category: 'overlay' },
  { name: 'JustIconButton', slug: 'icon-button', category: 'composite' },
  { name: 'JustInput', slug: 'input', category: 'primitive' },
  { name: 'JustProgress', slug: 'progress', category: 'primitive' },
  { name: 'JustRadio', slug: 'radio', category: 'selection' },
  { name: 'JustRadioGroup', slug: 'radio-group', category: 'composite' },
  { name: 'JustResizable', slug: 'resizable', category: 'layout' },
  { name: 'JustScrollArea', slug: 'scroll-area', category: 'layout' },
  { name: 'JustSelect', slug: 'select', category: 'primitive' },
  { name: 'JustSeparator', slug: 'separator', category: 'layout' },
  { name: 'JustSheet', slug: 'sheet', category: 'overlay' },
  { name: 'JustSidebar', slug: 'sidebar', category: 'navigation' },
  { name: 'JustSkeleton', slug: 'skeleton', category: 'layout' },
  { name: 'JustSlider', slug: 'slider', category: 'form' },
  { name: 'JustSwitch', slug: 'switch', category: 'selection' },
  { name: 'JustTable', slug: 'table', category: 'primitive' },
  { name: 'JustTabs', slug: 'tabs', category: 'navigation' },
  { name: 'JustTimePicker', slug: 'time-picker', category: 'composite' },
  { name: 'JustToast', slug: 'toast', category: 'overlay' },
  { name: 'JustToggle', slug: 'toggle', category: 'primitive' },
  { name: 'JustTooltip', slug: 'tooltip', category: 'overlay' },
] as const;

/** `version` in packages/cli/Cargo.toml. */
export const CLI_VERSION = '0.14.0';
/** `version` in registry/index.json. */
export const REGISTRY_VERSION = '0.14.0';
export const REGISTRY_PRESETS: readonly string[] = ['default', 'neobrutalism'];

/** Defaults from packages/cli/src/config.rs (`justui init -y`). */
export const CLI_DEFAULTS = {
  registryUrl:
    'https://raw.githubusercontent.com/infinitedim/justui/main/registry',
  componentsDir: 'lib/widgets',
  sharedDir: 'lib/widgets/shared',
  tokensDir: 'lib/tokens',
} as const;

export interface GeneratedRegistryEntry {
  readonly name: string;
  readonly category: string;
  readonly internal: boolean;
  readonly description: string;
  /** File names in the order the CLI copies them (common, then default). */
  readonly files: readonly string[];
  readonly registryDependencies: readonly string[];
  readonly supportedPresets: readonly string[];
  /** ThemeExtension the CLI registers in theme_data_material.dart. */
  readonly themeClass: string | null;
}

/** Every registry entry, internal ones included, in registry order. */
export const GENERATED_REGISTRY: readonly GeneratedRegistryEntry[] = [
  {
    name: 'button',
    category: 'primitive',
    internal: false,
    description:
      'Versatile interactive button with dynamic variant and scale-down state animations.',
    files: [
      'just_button_theme.dart',
      'just_button_variants.dart',
      'just_button_style.dart',
      'just_button.dart',
      'just_icon_button.dart',
    ],
    registryDependencies: [
      '_shared_pressable',
      '_shared_focus_indicator',
      '_shared_progress_spinner',
    ],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustButtonTheme',
  },
  {
    name: 'icon-button',
    category: 'composite',
    internal: false,
    description:
      'Premium icon button with tooltip assertions and press interactions. Requires base button component.',
    files: ['just_icon_button.dart'],
    registryDependencies: [
      'button',
      '_shared_pressable',
      '_shared_focus_indicator',
      '_shared_progress_spinner',
    ],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: null,
  },
  {
    name: 'input',
    category: 'primitive',
    internal: false,
    description:
      'Interactive text field component with dynamic label animations and form state bindings.',
    files: [
      'just_input_variants.dart',
      'just_input_theme.dart',
      'just_input_style.dart',
      'just_input.dart',
    ],
    registryDependencies: [],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustInputTheme',
  },
  {
    name: 'badge',
    category: 'primitive',
    internal: false,
    description:
      'Tag indicator widget supporting outline states and animated pulsing dot halos.',
    files: [
      'just_badge_style.dart',
      'just_badge_variants.dart',
      'just_badge.dart',
    ],
    registryDependencies: [],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: null,
  },
  {
    name: 'avatar',
    category: 'primitive',
    internal: false,
    description:
      'Image avatar with fallback initials generator and presence status indicators.',
    files: [
      'just_avatar_style.dart',
      'just_avatar_variants.dart',
      'just_avatar.dart',
      'just_avatar_group.dart',
    ],
    registryDependencies: ['_shared_pressable', '_shared_focus_indicator'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: null,
  },
  {
    name: 'avatar-group',
    category: 'composite',
    internal: false,
    description:
      'Avatar stack container displaying overlapping avatars with remainder counts. Requires base avatar component.',
    files: ['just_avatar_group.dart'],
    registryDependencies: ['avatar'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: null,
  },
  {
    name: 'checkbox',
    category: 'selection',
    internal: false,
    description:
      'High-performance checkbox selection primitive supporting checked, unchecked, and mixed states.',
    files: [
      'just_checkbox_style.dart',
      'just_checkbox_theme.dart',
      'just_checkbox.dart',
    ],
    registryDependencies: ['_shared_pressable', '_shared_focus_indicator'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustCheckboxTheme',
  },
  {
    name: 'radio',
    category: 'selection',
    internal: false,
    description:
      'High-performance radio button selection primitive with custom paint animations.',
    files: [
      'just_radio_theme.dart',
      'just_radio_style.dart',
      'just_radio.dart',
      'just_radio_group.dart',
    ],
    registryDependencies: ['_shared_pressable', '_shared_focus_indicator'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustRadioTheme',
  },
  {
    name: 'radio-group',
    category: 'composite',
    internal: false,
    description:
      'Radio button container laying out radio options in horizontal or vertical lists. Requires base radio component.',
    files: ['just_radio_group.dart'],
    registryDependencies: ['radio'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: null,
  },
  {
    name: 'switch',
    category: 'selection',
    internal: false,
    description:
      'Premium animated toggle switch component with tap and horizontal drag gestures.',
    files: [
      'just_switch_style.dart',
      'just_switch_theme.dart',
      'just_switch.dart',
    ],
    registryDependencies: ['_shared_pressable', '_shared_focus_indicator'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustSwitchTheme',
  },
  {
    name: 'card',
    category: 'layout',
    internal: false,
    description:
      'Customizable content card supporting elevated, outlined, and filled states.',
    files: ['just_card_style.dart', 'just_card_theme.dart', 'just_card.dart'],
    registryDependencies: ['_shared_pressable', '_shared_focus_indicator'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustCardTheme',
  },
  {
    name: 'separator',
    category: 'layout',
    internal: false,
    description:
      'Visual divider widget supporting horizontal and vertical directions and centered text labels.',
    files: [
      'just_separator_style.dart',
      'just_separator_theme.dart',
      'just_separator.dart',
    ],
    registryDependencies: [],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustSeparatorTheme',
  },
  {
    name: 'scroll-area',
    category: 'layout',
    internal: false,
    description:
      'Performance-optimized scroll viewport with custom scrollbars, fade edges, and scroll-to-top overlays.',
    files: [
      'just_scroll_area_theme.dart',
      'just_scroll_area_style.dart',
      'just_scroll_area.dart',
    ],
    registryDependencies: ['_shared_pressable', '_shared_focus_indicator'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustScrollAreaTheme',
  },
  {
    name: 'resizable',
    category: 'layout',
    internal: false,
    description:
      'Flexible resizable panel layout with isolated fraction drag math, keyboard navigation, and splitter handles.',
    files: [
      'just_resizable_variants.dart',
      'just_resizable_theme.dart',
      'just_resizable_style.dart',
      'just_resizable.dart',
    ],
    registryDependencies: ['_shared_focus_indicator'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustResizableTheme',
  },
  {
    name: 'carousel',
    category: 'layout',
    internal: false,
    description:
      'Accessible and performant carousel with infinite looping, auto-scroll, interactive indicators, and smooth transitions.',
    files: [
      'just_carousel_variants.dart',
      'just_carousel_theme.dart',
      'just_carousel_style.dart',
      'just_carousel.dart',
    ],
    registryDependencies: ['_shared_pressable', '_shared_focus_indicator'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustCarouselTheme',
  },
  {
    name: '_shared_pressable',
    category: 'internal',
    internal: true,
    description: 'Internal shared interactive press/hover state tracker.',
    files: ['_shared_pressable.dart'],
    registryDependencies: [],
    supportedPresets: ['default'],
    themeClass: null,
  },
  {
    name: '_shared_focus_indicator',
    category: 'internal',
    internal: true,
    description: 'Internal shared focus outline indicator ring overlay.',
    files: ['_shared_focus_indicator.dart'],
    registryDependencies: [],
    supportedPresets: ['default'],
    themeClass: null,
  },
  {
    name: 'skeleton',
    category: 'layout',
    internal: false,
    description:
      'Structure-aware skeleton loading placeholder with recursive transformation and custom manual shape named constructors.',
    files: [
      'just_skeleton_style.dart',
      'just_skeleton_theme.dart',
      'just_skeleton.dart',
    ],
    registryDependencies: [
      'avatar',
      'badge',
      'button',
      'card',
      'separator',
      '_shared_progress_spinner',
    ],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustSkeletonTheme',
  },
  {
    name: 'slider',
    category: 'form',
    internal: false,
    description:
      'Accessible and performant slider component for single value and range selection.',
    files: [
      'just_slider_theme.dart',
      'just_slider_style.dart',
      'just_slider.dart',
    ],
    registryDependencies: ['_shared_focus_indicator'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustSliderTheme',
  },
  {
    name: '_shared_progress_spinner',
    category: 'internal',
    internal: true,
    description: 'Internal shared rotatory loading progress spinner.',
    files: ['_shared_progress_spinner.dart'],
    registryDependencies: [],
    supportedPresets: ['default'],
    themeClass: null,
  },
  {
    name: 'breadcrumb',
    category: 'navigation',
    internal: false,
    description:
      'Premium text link layout breadcrumbs with collapsible middle items and custom overlay dropdown.',
    files: [
      'just_breadcrumb_theme.dart',
      'just_breadcrumb_style.dart',
      'just_breadcrumb_variants.dart',
      'just_breadcrumb.dart',
    ],
    registryDependencies: ['_shared_pressable'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustBreadcrumbTheme',
  },
  {
    name: 'tabs',
    category: 'navigation',
    internal: false,
    description:
      'Tabs component supporting line, enclosed, pill, and vertical variants with lazy loading and keyboard navigation.',
    files: [
      'just_tabs_variants.dart',
      'just_tabs_style.dart',
      'just_tabs_theme.dart',
      'just_tabs.dart',
      'just_tab_indicator.dart',
    ],
    registryDependencies: ['_shared_pressable'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustTabsTheme',
  },
  {
    name: 'bottom-nav',
    category: 'navigation',
    internal: false,
    description:
      'Navigation bar component supporting fixed, shifting, and floating layout structures.',
    files: [
      'just_bottom_nav_theme.dart',
      'just_bottom_nav_variants.dart',
      'just_bottom_nav_style.dart',
      'just_bottom_nav.dart',
    ],
    registryDependencies: ['_shared_pressable'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustBottomNavTheme',
  },
  {
    name: '_shared_overlay_transition',
    category: 'internal',
    internal: true,
    description: 'Internal shared overlay transition animations.',
    files: ['_shared_overlay_transition.dart'],
    registryDependencies: [],
    supportedPresets: ['default'],
    themeClass: null,
  },
  {
    name: '_shared_tooltip_overlay',
    category: 'internal',
    internal: true,
    description: 'Internal shared layout-phase tooltip overlay portal.',
    files: ['_shared_tooltip_overlay.dart'],
    registryDependencies: ['tooltip'],
    supportedPresets: ['default'],
    themeClass: null,
  },
  {
    name: 'sidebar',
    category: 'navigation',
    internal: false,
    description:
      'Collapsible navigation sidebar supporting recursive folder sub-menus and hover tooltips.',
    files: [
      'just_sidebar_variants.dart',
      'just_sidebar_style.dart',
      'just_sidebar_theme.dart',
      'just_sidebar.dart',
    ],
    registryDependencies: ['_shared_pressable', '_shared_tooltip_overlay'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustSidebarTheme',
  },
  {
    name: 'toast',
    category: 'overlay',
    internal: false,
    description:
      'Stacked/queued notification toasts with auto-dismiss, swipe-to-dismiss, and variant icons.',
    files: [
      'just_toast_theme.dart',
      'just_toast_style.dart',
      'just_toast_variants.dart',
      'just_toast.dart',
    ],
    registryDependencies: [],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustToastTheme',
  },
  {
    name: 'dialog',
    category: 'overlay',
    internal: false,
    description:
      'Modal dialog overlay with barrier, focus trapping, and position-aware animations.',
    files: [
      'just_dialog_variants.dart',
      'just_dialog_theme.dart',
      'just_dialog_style.dart',
      'just_dialog.dart',
    ],
    registryDependencies: [],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustDialogTheme',
  },
  {
    name: 'sheet',
    category: 'overlay',
    internal: false,
    description:
      'Slide-in sheet overlay with drag-to-dismiss, directional animations, and barrier support.',
    files: [
      'just_sheet_variants.dart',
      'just_sheet_style.dart',
      'just_sheet_theme.dart',
      'just_sheet.dart',
    ],
    registryDependencies: [],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustSheetTheme',
  },
  {
    name: 'tooltip',
    category: 'overlay',
    internal: false,
    description:
      'Declarative tooltip widget with auto-positioning, hover/long-press triggers, and delay controls.',
    files: [
      'just_tooltip_theme.dart',
      'just_tooltip_style.dart',
      'just_tooltip_variants.dart',
      'just_tooltip.dart',
    ],
    registryDependencies: [],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustTooltipTheme',
  },
  {
    name: 'select',
    category: 'primitive',
    internal: false,
    description:
      'Dropdown select component with customizable overlay positioning and optional search filter.',
    files: [
      'just_select_theme.dart',
      'just_select_style.dart',
      'just_select_variants.dart',
      'just_select.dart',
    ],
    registryDependencies: ['_shared_pressable', '_shared_focus_indicator'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustSelectTheme',
  },
  {
    name: 'progress',
    category: 'primitive',
    internal: false,
    description:
      'Linear progress bar and circular progress indicator supporting both determinate and indeterminate states.',
    files: [
      'just_progress_style.dart',
      'just_progress_variants.dart',
      'just_progress_theme.dart',
      'just_progress.dart',
    ],
    registryDependencies: [],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustProgressTheme',
  },
  {
    name: 'accordion',
    category: 'primitive',
    internal: false,
    description:
      'Expandable panel accordion with single-expand or multi-expand modes.',
    files: [
      'just_accordion_style.dart',
      'just_accordion_theme.dart',
      'just_accordion_variants.dart',
      'just_accordion.dart',
    ],
    registryDependencies: ['_shared_pressable', '_shared_focus_indicator'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustAccordionTheme',
  },
  {
    name: 'toggle',
    category: 'primitive',
    internal: false,
    description:
      'Single toggle button and toggle groups for radio or checkbox behaviors.',
    files: [
      'just_toggle_theme.dart',
      'just_toggle_variants.dart',
      'just_toggle_style.dart',
      'just_toggle.dart',
      'just_toggle_group.dart',
    ],
    registryDependencies: ['_shared_pressable', '_shared_focus_indicator'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustToggleTheme',
  },
  {
    name: 'table',
    category: 'primitive',
    internal: false,
    description: 'Data table supporting sorting, selection, and sticky header.',
    files: [
      'just_table_variants.dart',
      'just_table_theme.dart',
      'just_table_style.dart',
      'just_table.dart',
    ],
    registryDependencies: ['_shared_pressable', '_shared_focus_indicator'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustTableTheme',
  },
  {
    name: 'date-picker',
    category: 'composite',
    internal: false,
    description:
      'Full-featured calendar date picker with inline, modal, and dropdown variants.',
    files: [
      'just_date_picker_variants.dart',
      'just_date_picker_style.dart',
      'just_date_picker_theme.dart',
      'just_date_picker.dart',
      '_date_picker_calendar.dart',
    ],
    registryDependencies: [
      '_shared_pressable',
      '_shared_focus_indicator',
      '_shared_overlay_transition',
      'dialog',
      'sheet',
    ],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustDatePickerTheme',
  },
  {
    name: 'date-range-picker',
    category: 'composite',
    internal: false,
    description:
      'Date range selection picker with quick presets (Today, Last 7 Days, etc.).',
    files: ['just_date_range_picker.dart'],
    registryDependencies: ['date-picker', '_shared_pressable'],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: null,
  },
  {
    name: 'time-picker',
    category: 'composite',
    internal: false,
    description:
      'Full-featured clock time picker with dial, spinner, and direct numeric input modes.',
    files: [
      'just_time_picker_variants.dart',
      'just_time_picker_style.dart',
      'just_time_picker_theme.dart',
      'just_time_picker.dart',
      '_time_picker_dial.dart',
      '_time_picker_spinner.dart',
      '_time_picker_input.dart',
    ],
    registryDependencies: [
      'button',
      'input',
      '_shared_pressable',
      '_shared_focus_indicator',
      '_shared_overlay_transition',
      'dialog',
      'sheet',
    ],
    supportedPresets: ['default', 'neobrutalism'],
    themeClass: 'JustTimePickerTheme',
  },
] as const;
