import 'package:flutter/material.dart';

import 'core/just_ui_core.dart';
import 'core/theme/just_theme.dart';
import 'widgets/badge/just_badge.dart';
import 'widgets/button/just_button.dart';
import 'widgets/card/just_card.dart';
import 'widgets/checkbox/just_checkbox.dart';
import 'widgets/input/just_input.dart';
import 'widgets/progress/just_progress.dart';
import 'widgets/select/just_select.dart';
import 'widgets/separator/just_separator.dart';
import 'widgets/switch/just_switch.dart';

/// CLI sandbox for JustUI.
///
/// Everything under `lib/core`, `lib/tokens` and `lib/widgets` is generated by
/// `justui init` + `justui add --all` against the local `../../registry`, so
/// this app is the end-to-end check that installed components compile and
/// render. Regenerate it instead of editing those folders by hand.
void main() {
  runApp(const ShowcaseApp());
}

class ShowcaseApp extends StatelessWidget {
  const ShowcaseApp({super.key});

  @override
  Widget build(BuildContext context) {
    return JustThemeProvider(
      lightTheme: justThemeLight,
      darkTheme: justThemeDark,
      child: Builder(
        builder: (BuildContext context) {
          final JustThemeData theme = context.justTheme;
          return MaterialApp(
            title: 'JustUI CLI Sandbox',
            debugShowCheckedModeBanner: false,
            theme: theme.toThemeData(),
            home: const ComponentGallery(),
          );
        },
      ),
    );
  }
}

/// Scrollable gallery with one section per installed component family.
class ComponentGallery extends StatefulWidget {
  const ComponentGallery({super.key});

  @override
  State<ComponentGallery> createState() => _ComponentGalleryState();
}

class _ComponentGalleryState extends State<ComponentGallery> {
  bool _checked = true;
  bool _switchedOn = false;
  String? _framework = 'flutter';

  @override
  Widget build(BuildContext context) {
    final JustSpacingScheme spacing = context.justSpacing;
    final JustTypographyScheme typo = context.justTypo;

    return Scaffold(
      body: SafeArea(
        child: ListView(
          padding: .all(spacing.xl),
          children: <Widget>[
            Text('JustUI CLI Sandbox', style: typo.headingLg),
            SizedBox(height: spacing.xs),
            Text(
              'Components installed with `justui add --all`.',
              style: typo.bodyMd,
            ),
            SizedBox(height: spacing.xl),
            _Section(
              title: 'Button',
              child: Wrap(
                spacing: spacing.sm,
                runSpacing: spacing.sm,
                children: <Widget>[
                  JustButton(label: 'Primary', onPressed: () {}),
                  JustButton(
                    label: 'Secondary',
                    variant: .secondary,
                    onPressed: () {},
                  ),
                  JustButton(label: 'Ghost', variant: .ghost, onPressed: () {}),
                  const JustButton(label: 'Disabled', onPressed: null),
                ],
              ),
            ),
            _Section(
              title: 'Badge',
              child: Wrap(
                spacing: spacing.sm,
                children: const <Widget>[
                  JustBadge(label: 'Solid'),
                  JustBadge(label: 'Outline', variant: .outline),
                  JustBadge(label: 'Soft', variant: .soft),
                ],
              ),
            ),
            _Section(
              title: 'Selection',
              child: Row(
                children: <Widget>[
                  JustCheckbox(
                    value: _checked,
                    onChanged: (bool? value) =>
                        setState(() => _checked = value ?? false),
                  ),
                  SizedBox(width: spacing.lg),
                  JustSwitch(
                    value: _switchedOn,
                    onChanged: (bool value) =>
                        setState(() => _switchedOn = value),
                  ),
                ],
              ),
            ),
            _Section(
              title: 'Input & Select',
              child: Column(
                crossAxisAlignment: .stretch,
                children: <Widget>[
                  const JustInput(label: 'Project name', hint: 'my_app'),
                  SizedBox(height: spacing.md),
                  JustSelect<String>(
                    label: 'Framework',
                    value: _framework,
                    onChanged: (String value) =>
                        setState(() => _framework = value),
                    options: const <JustSelectOption<String>>[
                      JustSelectOption<String>(
                        value: 'flutter',
                        label: 'Flutter',
                      ),
                      JustSelectOption<String>(value: 'dart', label: 'Dart'),
                    ],
                  ),
                ],
              ),
            ),
            _Section(
              title: 'Card & Progress',
              child: JustCard(
                child: Column(
                  crossAxisAlignment: .start,
                  children: <Widget>[
                    Text('Install progress', style: typo.bodyMd),
                    SizedBox(height: spacing.sm),
                    const JustProgress(value: 0.6),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class _Section extends StatelessWidget {
  const _Section({required this.title, required this.child});

  final String title;
  final Widget child;

  @override
  Widget build(BuildContext context) {
    final JustSpacingScheme spacing = context.justSpacing;
    return Padding(
      padding: .only(bottom: spacing.xl),
      child: Column(
        crossAxisAlignment: .start,
        children: <Widget>[
          Text(title, style: context.justTypo.headingSm),
          SizedBox(height: spacing.sm),
          const JustSeparator(),
          SizedBox(height: spacing.md),
          child,
        ],
      ),
    );
  }
}
